# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Mammad Mirza
description: "Hello, I’m Mammad, an inquisitive scientist with a PhD in Engineering and over 5 years of experience in optimization, control theory, computational modeling, and AI-driven solutions for energy systems. Expertise in developing scalable computational frameworks that integrate physics-based models, machine learning, and high-performance computing to solve complex industrial challenges.  Experienced in optimization algorithms, model predictive control, and differentiable programming using modern frameworks such as Casadi, JAX, PyTorch and TensorFlow. Demonstrated ability to rapidly prototype and deploy production-ready Gen-AI applications that enhance user experiences and operational efficiency, while adhering to responsible AI and data governance best practices."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Project <span style="color:#f58506"> Portfolio </span>
location: "Calgary, AB"
resume_url: /docs/resume.docx
avatar_image: /img/profile_picture.JPG

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/mammad-mirza#" # Add your linkedln handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false

# Markdown and Math Settings
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/













