# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Mammad Mirza, PhD
description: "Hello, I’m Mammad, a Reservoir Engineer and interdisciplinary researcher with a PhD in Chemical and Petroleum Engineering and over 10 years of experience in reservoir engineering, subsurface energy systems, computational modeling, optimization, and AI-driven solutions. My work spans reservoir characterization, unconventional reservoirs, CO₂ storage, geothermal energy systems, production optimization, tracer-test interpretation, hydraulic fracture diagnostics, and data-driven reservoir management. I have developed and applied reservoir simulation, machine learning, uncertainty quantification, and techno-economic assessment workflows to address complex challenges in energy production and the energy transition. By combining domain expertise with modern tools such as Python, JAX, PyTorch, and high-performance computing, I transform complex subsurface data into actionable insights that improve decision-making, operational performance, and the development of sustainable energy solutions. "


baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Project <span style="color:#f58506"> Portfolio </span>
location: "Calgary, AB"
resume_url: /docs/resume.docx
avatar_image: /img/profile_picture.JPG

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/mammad-mirza" # Add your linkedln handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      mathjax: true
      share: false

# Markdown and Math Settings
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/













