# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Mammad Mirza, PhD
description: "

Hello, I’m Mammad, a Reservoir Engineer and interdisciplinary researcher with a PhD in Chemical and Petroleum Engineering and over 10 years of experience spanning reservoir engineering, subsurface energy systems, computational modeling, optimization, and AI-driven solutions. My work has focused on reservoir characterization, interwell connectivity analysis, unconventional reservoirs, CO₂ storage, geothermal energy systems, production optimization, and data-driven reservoir management. I have developed and applied physics-based simulation models, machine learning methods, and uncertainty quantification workflows to address complex challenges in reservoir performance, fluid flow, carbon storage, and energy transition projects.
My expertise includes reservoir simulation, production optimization, tracer-test interpretation, hydraulic fracture communication analysis, techno-economic assessment, and the integration of machine learning with reservoir engineering workflows. I am experienced in developing scalable computational frameworks using Python, JAX, PyTorch, TensorFlow, and high-performance computing platforms to support decision-making under uncertainty. I also have a demonstrated ability to rapidly prototype and deploy AI-powered applications that transform technical data into actionable insights, improving operational efficiency and supporting innovation across the energy sector.
"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Project <span style="color:#f58506"> Portfolio </span>
location: "Calgary, AB"
resume_url: /docs/resume.docx
avatar_image: /img/profile_picture.JPG

#-------------------------------
# Contact links
linkedln: "" # Add your linkedln handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      mathjax: true
      share: false

# Markdown and Math Settings
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/













